Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -2,7 +2,7 @@
 
 name: CI
 on:
-  push:
+  pull_request:
     branches: [ master ]
 
 jobs:
@@ -13,12 +13,12 @@ jobs:
     steps:
     - uses: actions/checkout@v2
     - name: grep
-      run: echo v-10.0.0 | egrep "v[0-9]*\.[0-9]*\.[0-9]*" 
-    - name: Run failure script
-      if: failure()
-      run: |
-        echo failure
-    - name: Run success script
-      if: success()
-      run: |
-        echo success
+      env:
+        TITLE: ${{ github.event.pull_request.title }}
+      run: echo ${TITLE} | egrep "v[0-9]*\.[0-9]*\.[0-9]*" 
+#     - name: Run failure script
+#       if: failure()
+#       run: exit 1
+#     - name: Run success script
+#       if: success()
+#       run: exit 0
